/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/ui/button/Button.vue')['default']
    GameBoard: typeof import('./components/GameBoard.vue')['default']
    GameMenu: typeof import('./components/GameMenu.vue')['default']
    GameOver: typeof import('./components/GameOver.vue')['default']
  }
}
